<?php
namespace App\Command;

use App\Scheduler\CountResultImporter;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ImportResultCommand extends Command
{
    protected static $defaultName = 'app:result:import';

    public function __construct(
        private CountResultImporter $countResultImporter
    ) {
        parent::__construct();
    }

    protected function configure()
    {
        $this->setDescription("Imports input csv file generated by scheduler-calculator for given plan_id");
        $this->addArgument('plan_id', InputArgument::REQUIRED, 'Plan to be imported.');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $planId = $input->getArgument("plan_id");

        ($this->countResultImporter)($planId);

        return Command::SUCCESS;
    }
}
