framework:
    workflows:
        plan_status:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
#                originalMarkingStore: method
                type: method
#                service: 'App\Workflow\Persistent\Doctrine\DoctrinePersistentMarkingStore'
                property: 'status'
            supports:
                - App\Entity\Plan
            initial_marking: locked
            places:
                - under_construction
                - locked
                - event_filling_started
                - event_filling_finished
                - map_id_filling_started
                - map_id_filling_finished
                - normalized_data_generation_started
                - normalized_data_generation_finished
                - schedule_calculation_started
                - schedule_calculation_finished
                - normalisation_error
                - calculation_error
            transitions:
                locking:
                    from: under_construction
                    to:   locked
                event_filling_starting:
                    from: locked
                    to:   event_filling_started
                event_filling_finising:
                    from: event_filling_started
                    to:   event_filling_finished
                map_id_filling_starting:
                    from: event_filling_finished
                    to:   map_id_filling_started
                map_id_filling_finishing:
                    from: map_id_filling_started
                    to:   map_id_filling_finished
                normalized_data_generation_starting:
                    from: map_id_filling_finished
                    to:   normalized_data_generation_started
                normalized_data_generation_finishing:
                    from: normalized_data_generation_started
                    to:   normalized_data_generation_finished
                schedule_calculation_starting:
                    from: normalized_data_generation_finished
                    to:   schedule_calculation_started
                schedule_calculation_finishing:
                    from: schedule_calculation_started
                    to:   schedule_calculation_finished
                normalisation_error_rising:
                    from: [event_filling_started, map_id_filling_started, normalized_data_generation_started]
                    to:   normalisation_error
                calculation_error_rising:
                    from: schedule_calculation_started
                    to:   calculation_error
