framework:
    workflows:
        plan_status:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: method
                property: 'status'
            supports:
                - App\Entity\Plan
            initial_marking: locked
            places:
                - under_construction
                - locked
                - event_filling_started
                - event_filling_finished
                - map_id_filling_started
                - map_id_filling_finished
                - normalized_data_generation_started
                - normalized_data_generation_finished
                - calculation_started
                - calculation_finished
                - calculation_unsuccessful
                - result_import_started
                - result_import_finished
                - normalisation_error
                - calculation_error
                - result_import_error
            transitions:
                locking:
                    from: under_construction
                    to:   locked
                event_filling_starting:
                    from: locked
                    to:   event_filling_started
                event_filling_finishing:
                    from: event_filling_started
                    to:   event_filling_finished
                map_id_filling_starting:
                    from: event_filling_finished
                    to:   map_id_filling_started
                map_id_filling_finishing:
                    from: map_id_filling_started
                    to:   map_id_filling_finished
                normalized_data_generation_starting:
                    from: map_id_filling_finished
                    to:   normalized_data_generation_started
                normalized_data_generation_finishing:
                    from: normalized_data_generation_started
                    to:   normalized_data_generation_finished
                calculation_starting:
                    from: [normalized_data_generation_finished, result_import_finished, calculation_unsuccessful]
                    to:   calculation_started
                calculation_finishing:
                    from: calculation_started
                    to:   calculation_finished
                calculation_unsuccessful_marking:
                    from: calculation_started
                    to: calculation_unsuccessful
                result_import_starting:
                    from: calculation_finished
                    to:   result_import_started
                result_import_finishing:
                    from: result_import_started
                    to: result_import_finished
                normalisation_error_marking:
                    from: [event_filling_started, map_id_filling_started, normalized_data_generation_started]
                    to:   normalisation_error
                calculation_error_marking:
                    from: calculation_started
                    to:   calculation_error
                result_import_error_marking:
                    from: result_import_started
                    to:   result_import_error

