version: '3.5'
services:
  php:
    image: scheduler:latest
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    networks:
      - scheduler

  sql:
    image: mysql:8.0.23
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./data/sql:/var/lib/mysql
    networks:
      - scheduler

networks:
  scheduler:
    external:
      name: scheduler
