version: '2.0'
services:
  scheduler-server:
    build: .
    volumes:
      - ./:/var/www/
    ports:
      - "8080:80"
    networks:
      - scheduler-network

  sql:
    image: mysql:5.7.33
    ports:
      - "3316:3306"
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./.data:/var/lib/mysql
      - ./mysql/init.sql:/data/application/init.sql
    networks:
      - scheduler-network

networks:
  scheduler-network:
