version: '2.0'
services:
  scheduler-server:
    build: .
    image: scheduler-image
    restart: always
    volumes:
      - ./:/var/www/
    ports:
      - "8080:80"
    networks:
      - scheduler-network

  scheduler-consumer:
    image: scheduler-image
    restart: always
    volumes:
      - ./:/var/www/
    networks:
      - scheduler-network
    command: php bin/console messenger:consume async

  sql:
    image: mysql:5.7.33
    restart: always
#    ports:
#      - "3316:3306"
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./build/mysql/init.sql:/data/application/init.sql
    networks:
      - scheduler-network

  queue:
    image: rabbitmq:3.8.16-alpine
    restart: always
    networks:
      - scheduler-network
#    ports:
#      - 5672:5672
#      - 15672:15672
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit heartbeat 290
      RABBITMQ_DEFAULT_USER: scheduler
      RABBITMQ_DEFAULT_PASS: scheduler

networks:
  scheduler-network:
